# Generated by Django 4.2 on 2025-02-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='PRIDRIAN Luxe', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/logos/')),
                ('contact_email', models.EmailField(default='info@pridrianluxe.com', max_length=255)),
                ('contact_phone', models.CharField(default='070-020-0340', max_length=15)),
                ('business_address', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('enable_mpesa', models.BooleanField(default=True)),
                ('mpesa_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('enable_paypal', models.BooleanField(default=False)),
                ('paypal_client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('flat_shipping_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('enable_free_shipping', models.BooleanField(default=False)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('homepage_meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('homepage_meta_description', models.TextField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(default='We are currently performing maintenance. Please check back later.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
