# Generated by Django 4.2 on 2025-02-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='enable_visa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='visa_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
