# Generated by Django 4.2 on 2024-11-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_delete_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
