# Generated by Django 4.2 on 2024-11-30 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_account_delete_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
