# Generated by Django 4.2 on 2024-12-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=255)),
                ('colors', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='products/')),
                ('rating', models.FloatField(default=0.0)),
                ('comments_count', models.IntegerField(default=0)),
            ],
        ),
    ]
